# Generated by Django 3.0.7 on 2021-01-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition_facts',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
