# Generated by Django 3.0.7 on 2020-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0002_auto_20200628_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('ingrédients', models.TextField()),
                ('allergènes', models.CharField(max_length=100)),
                ('note_nutritionnelle', models.CharField(max_length=50)),
                ('magasins', models.CharField(max_length=150)),
                ('labels', models.TextField()),
                ('lien_OFF', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
