# Generated by Django 3.0.7 on 2020-06-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0004_auto_20200630_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nom',
        ),
    ]
