# Generated by Django 3.0.7 on 2020-07-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0009_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurreweb.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoriesAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurreweb.Categories')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurreweb.Product')),
            ],
            options={
                'unique_together': {('product_id', 'categories_id')},
            },
        ),
    ]
