# Generated by Django 3.0.7 on 2020-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0010_favorites_productcategoriesassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='corresponding_products',
            field=models.ManyToManyField(to='purbeurreweb.Product'),
        ),
        migrations.DeleteModel(
            name='ProductCategoriesAssociation',
        ),
    ]
