# Generated by Django 3.0.7 on 2020-07-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0011_auto_20200704_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategories',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='corresponding_products',
            new_name='products',
        ),
    ]
