# Generated by Django 3.0.7 on 2020-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0012_auto_20200704_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='products',
            field=models.ManyToManyField(blank=True, to='purbeurreweb.Product'),
        ),
    ]
