# Generated by Django 3.0.7 on 2020-07-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0014_auto_20200704_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purbeurreweb.Product'),
        ),
    ]
