# Generated by Django 3.0.7 on 2020-07-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0015_auto_20200704_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='purbeurreweb.Product'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purbeurreweb.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergènes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingrédients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lien_off',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='magasins',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='note_nutritionnelle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
