# Generated by Django 3.0.7 on 2020-07-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0016_auto_20200704_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='products',
            field=models.ManyToManyField(to='purbeurreweb.Product'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurreweb.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergènes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingrédients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='lien_off',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='magasins',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='note_nutritionnelle',
            field=models.CharField(max_length=50),
        ),
    ]
