# Generated by Django 3.0.7 on 2020-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0017_auto_20200704_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='purbeurreweb.Categories'),
        ),
    ]
