# Generated by Django 3.0.7 on 2020-07-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0018_auto_20200704_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='purbeurreweb.Categories'),
        ),
    ]
