# Generated by Django 3.0.7 on 2020-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0019_auto_20200704_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='purbeurreweb.Categories'),
        ),
    ]
