# Generated by Django 3.0.7 on 2020-07-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0020_auto_20200704_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
