# Generated by Django 3.0.7 on 2020-07-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0021_auto_20200704_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.TextField(),
        ),
    ]
