# Generated by Django 3.0.7 on 2020-07-05 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurreweb', '0022_auto_20200705_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
