# Generated by Django 3.0.7 on 2020-07-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0024_auto_20200720_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categories',
            new_name='name',
        ),
    ]
