# Generated by Django 3.0.7 on 2020-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0025_auto_20200720_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
