# Generated by Django 3.0.7 on 2020-07-21 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurreweb', '0026_auto_20200720_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
    ]
