# Generated by Django 3.0.7 on 2020-07-21 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurreweb', '0027_auto_20200721_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favorites',
        ),
    ]
