# Generated by Django 3.0.7 on 2020-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0029_auto_20200721_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='purbeurreweb.Categorie'),
        ),
    ]
