# Generated by Django 3.0.7 on 2020-08-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0030_auto_20200808_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergènes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='lien_off',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='magasins',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
