# Generated by Django 3.0.7 on 2020-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0031_auto_20200812_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergènes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='lien_off',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='magasins',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
