# Generated by Django 3.0.7 on 2020-08-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0032_auto_20200812_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product_name',
            field=models.CharField(default='favoris', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='purbeurreweb.Favorite'),
        ),
    ]
