# Generated by Django 3.0.7 on 2020-10-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0033_auto_20200813_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
