# Generated by Django 3.0.7 on 2020-10-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0034_auto_20201026_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='allergènes',
            new_name='allergenes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='marque',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='favoris',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ingrédients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='note_nutritionnelle',
            new_name='nutriscore',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lien_off',
            new_name='off_link',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='magasins',
            new_name='shops',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product_name',
            field=models.CharField(default='favorites', max_length=500, unique=True),
        ),
    ]
