# Generated by Django 3.0.7 on 2020-10-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0035_auto_20201029_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='allergenes',
            new_name='allergens',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shops',
            new_name='stores',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='off_link',
            new_name='url',
        ),
    ]
