# Generated by Django 3.0.7 on 2020-11-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0036_auto_20201029_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorites',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
