# Generated by Django 3.0.7 on 2021-01-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purbeurreweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_favorites', to='purbeurreweb.Product')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favorites', to='purbeurreweb.Product')),
            ],
        ),
    ]
