# Generated by Django 3.0.7 on 2020-11-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purbeurreweb', '0037_auto_20201110_2203'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='purbeurreweb.Product')),
                ('user', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
