language: python
python:
  - '3.8.6'

addons:
    chrome: stable

before_script:
  - pip install -r requirements.txt
  - wget https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8.6/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"

services:
  - postgresql

script:
  - ./manage.py test
