# Generated by Django 3.0.7 on 2021-02-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('brand', models.CharField(max_length=500)),
                ('ingredients', models.TextField()),
                ('allergens', models.CharField(max_length=500)),
                ('nutriscore', models.CharField(max_length=50)),
                ('stores', models.CharField(max_length=500)),
                ('labels', models.TextField()),
                ('url', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('nutrition_facts', models.CharField(max_length=500)),
                ('categories', models.ManyToManyField(related_name='products', to='food.Category')),
            ],
        ),
    ]
