# Generated by Django 3.0.7 on 2021-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
