# Generated by Django 3.0.7 on 2021-01-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_has_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='has_favorites',
            new_name='has_favorite',
        ),
    ]
