# Generated by Django 3.0.7 on 2021-01-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210116_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='has_favorite',
        ),
    ]
