# Generated by Django 3.0.7 on 2020-06-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0005_auto_20200630_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lien_OFF',
            new_name='lien_off',
        ),
    ]
