# Generated by Django 3.0.7 on 2020-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurreweb', '0006_auto_20200630_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='products_pics'),
        ),
    ]
